package vision

type CityScapeClass struct {
	Name         string
	ID           int64
	TrainID      int64
	Category     string
	CategoryID   int64
	HasInstances bool
	IgnoreInEval bool
	Color        []uint8
}

var CityScapeClasses []CityScapeClass

func init() {
	CityScapeClasses = []CityScapeClass{
		CityScapeClass{
			Name:         "unlabeled",
			ID:           0,
			TrainID:      255,
			Category:     "void",
			CategoryID:   0,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(0), uint8(0), uint8(0)},
		},
		CityScapeClass{
			Name:         "ego vehicle",
			ID:           1,
			TrainID:      255,
			Category:     "void",
			CategoryID:   0,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(0), uint8(0), uint8(0)},
		},
		CityScapeClass{
			Name:         "rectification border",
			ID:           2,
			TrainID:      255,
			Category:     "void",
			CategoryID:   0,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(0), uint8(0), uint8(0)},
		},
		CityScapeClass{
			Name:         "out of roi",
			ID:           3,
			TrainID:      255,
			Category:     "void",
			CategoryID:   0,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(0), uint8(0), uint8(0)},
		},
		CityScapeClass{
			Name:         "static",
			ID:           4,
			TrainID:      255,
			Category:     "void",
			CategoryID:   0,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(0), uint8(0), uint8(0)},
		},
		CityScapeClass{
			Name:         "dynamic",
			ID:           5,
			TrainID:      255,
			Category:     "void",
			CategoryID:   0,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(111), uint8(74), uint8(0)},
		},
		CityScapeClass{
			Name:         "ground",
			ID:           6,
			TrainID:      255,
			Category:     "void",
			CategoryID:   0,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(81), uint8(0), uint8(81)},
		},
		CityScapeClass{
			Name:         "road",
			ID:           7,
			TrainID:      0,
			Category:     "flat",
			CategoryID:   1,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(128), uint8(64), uint8(128)},
		},
		CityScapeClass{
			Name:         "sidewalk",
			ID:           8,
			TrainID:      1,
			Category:     "flat",
			CategoryID:   1,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(244), uint8(35), uint8(232)},
		},
		CityScapeClass{
			Name:         "parking",
			ID:           9,
			TrainID:      255,
			Category:     "flat",
			CategoryID:   1,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(250), uint8(170), uint8(160)},
		},
		CityScapeClass{
			Name:         "rail track",
			ID:           10,
			TrainID:      255,
			Category:     "flat",
			CategoryID:   1,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(230), uint8(150), uint8(140)},
		},
		CityScapeClass{
			Name:         "building",
			ID:           11,
			TrainID:      2,
			Category:     "construction",
			CategoryID:   2,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(70), uint8(70), uint8(70)},
		},
		CityScapeClass{
			Name:         "wall",
			ID:           12,
			TrainID:      3,
			Category:     "construction",
			CategoryID:   2,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(102), uint8(102), uint8(156)},
		},
		CityScapeClass{
			Name:         "fence",
			ID:           13,
			TrainID:      4,
			Category:     "construction",
			CategoryID:   2,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(190), uint8(153), uint8(153)},
		},
		CityScapeClass{
			Name:         "guard rail",
			ID:           14,
			TrainID:      255,
			Category:     "construction",
			CategoryID:   2,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(180), uint8(165), uint8(180)},
		},
		CityScapeClass{
			Name:         "bridge",
			ID:           15,
			TrainID:      255,
			Category:     "construction",
			CategoryID:   2,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(150), uint8(100), uint8(100)},
		},
		CityScapeClass{
			Name:         "tunnel",
			ID:           16,
			TrainID:      255,
			Category:     "construction",
			CategoryID:   2,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(150), uint8(120), uint8(90)},
		},
		CityScapeClass{
			Name:         "pole",
			ID:           17,
			TrainID:      5,
			Category:     "object",
			CategoryID:   3,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(153), uint8(153), uint8(153)},
		},
		CityScapeClass{
			Name:         "polegroup",
			ID:           18,
			TrainID:      255,
			Category:     "object",
			CategoryID:   3,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(153), uint8(153), uint8(153)},
		},
		CityScapeClass{
			Name:         "traffic light",
			ID:           19,
			TrainID:      6,
			Category:     "object",
			CategoryID:   3,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(250), uint8(170), uint8(30)},
		},
		CityScapeClass{
			Name:         "traffic sign",
			ID:           20,
			TrainID:      7,
			Category:     "object",
			CategoryID:   3,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(220), uint8(220), uint8(0)},
		},
		CityScapeClass{
			Name:         "vegetation",
			ID:           21,
			TrainID:      8,
			Category:     "nature",
			CategoryID:   4,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(107), uint8(142), uint8(35)},
		},
		CityScapeClass{
			Name:         "terrain",
			ID:           22,
			TrainID:      9,
			Category:     "nature",
			CategoryID:   4,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(152), uint8(251), uint8(152)},
		},
		CityScapeClass{
			Name:         "sky",
			ID:           23,
			TrainID:      10,
			Category:     "sky",
			CategoryID:   5,
			HasInstances: false,
			IgnoreInEval: false,
			Color:        []uint8{uint8(70), uint8(130), uint8(180)},
		},
		CityScapeClass{
			Name:         "person",
			ID:           24,
			TrainID:      11,
			Category:     "human",
			CategoryID:   6,
			HasInstances: true,
			IgnoreInEval: false,
			Color:        []uint8{uint8(220), uint8(20), uint8(60)},
		},
		CityScapeClass{
			Name:         "rider",
			ID:           25,
			TrainID:      12,
			Category:     "human",
			CategoryID:   6,
			HasInstances: true,
			IgnoreInEval: false,
			Color:        []uint8{uint8(255), uint8(0), uint8(0)},
		},
		CityScapeClass{
			Name:         "car",
			ID:           26,
			TrainID:      13,
			Category:     "vehicle",
			CategoryID:   7,
			HasInstances: true,
			IgnoreInEval: false,
			Color:        []uint8{uint8(0), uint8(0), uint8(142)},
		},
		CityScapeClass{
			Name:         "truck",
			ID:           27,
			TrainID:      14,
			Category:     "vehicle",
			CategoryID:   7,
			HasInstances: true,
			IgnoreInEval: false,
			Color:        []uint8{uint8(0), uint8(0), uint8(70)},
		},
		CityScapeClass{
			Name:         "bus",
			ID:           28,
			TrainID:      15,
			Category:     "vehicle",
			CategoryID:   7,
			HasInstances: true,
			IgnoreInEval: false,
			Color:        []uint8{uint8(0), uint8(60), uint8(100)},
		},
		CityScapeClass{
			Name:         "caravan",
			ID:           29,
			TrainID:      255,
			Category:     "vehicle",
			CategoryID:   7,
			HasInstances: true,
			IgnoreInEval: true,
			Color:        []uint8{uint8(0), uint8(0), uint8(90)},
		},
		CityScapeClass{
			Name:         "trailer",
			ID:           30,
			TrainID:      255,
			Category:     "vehicle",
			CategoryID:   7,
			HasInstances: true,
			IgnoreInEval: true,
			Color:        []uint8{uint8(0), uint8(0), uint8(110)},
		},
		CityScapeClass{
			Name:         "train",
			ID:           31,
			TrainID:      16,
			Category:     "vehicle",
			CategoryID:   7,
			HasInstances: true,
			IgnoreInEval: false,
			Color:        []uint8{uint8(0), uint8(80), uint8(100)},
		},
		CityScapeClass{
			Name:         "motorcycle",
			ID:           32,
			TrainID:      17,
			Category:     "vehicle",
			CategoryID:   7,
			HasInstances: true,
			IgnoreInEval: false,
			Color:        []uint8{uint8(0), uint8(0), uint8(230)},
		},
		CityScapeClass{
			Name:         "bicycle",
			ID:           33,
			TrainID:      18,
			Category:     "vehicle",
			CategoryID:   7,
			HasInstances: true,
			IgnoreInEval: false,
			Color:        []uint8{uint8(119), uint8(11), uint8(32)},
		},
		CityScapeClass{
			Name:         "license plate",
			ID:           -1,
			TrainID:      -1,
			Category:     "vehicle",
			CategoryID:   7,
			HasInstances: false,
			IgnoreInEval: true,
			Color:        []uint8{uint8(0), uint8(0), uint8(142)},
		},
	}
}
